use_frameworks!

target 'Activ5-Device_Example' do
  pod 'Activ5BLE', :git => 'https://github.com/ActivBody/activ5-ble-ios'

  target 'Activ5-Device_Tests' do
    inherit! :search_paths
    
  end
end
